"""empty message

Revision ID: 8739c31339d0
Revises: c36221e64ed4
Create Date: 2020-06-26 17:10:59.485359

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8739c31339d0'
down_revision = 'c36221e64ed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
                    sa.Column('name2', sa.VARCHAR(length=80), nullable=False),
                    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
                    sa.Column('extend_one', sa.VARCHAR(length=81), nullable=True),
                    sa.Column('extend_two', sa.VARCHAR(length=80), nullable=True),
                    sa.Column('note', sa.VARCHAR(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('name'),
                    sa.UniqueConstraint('name2')
                    )
    # ### end Alembic commands ###
